name: Gas snapshot

on: [push]

env:
  FOUNDRY_PROFILE: ci

jobs:
  snapshot:
    strategy:
      fail-fast: true

    name: Gas snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Foundry shallow install
        run: forge install --shallow

      - name: Check gas snapshots
        run: forge snapshot --check
        id: snapshot
